name: Go

#TODO: extend the conditions once workflow gets tested together with other workflows
on:
  push:
    branches:
      # - master
  pull_request:
    # types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  build-and-test:
    if: github.event.pull_request.closed != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo df -h

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - run: sudo df -h

      - run: ls -l /tmp/.buildx-cache

      - name: Run Docker go-build-env
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          target: gobuild
          tags: go-build-env
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Docker go-build-env
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: keep-client
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - run: sudo df -h
      - run: ls -l /tmp/.buildx-cache

      # - name: Create test results directory
      #   run: |
      #     mkdir test-results
      # - name: Run Go tests
      #   run: |
      #     docker run \
      #       --volume $GITHUB_WORKSPACE/test-results:/mnt/test-results \
      #       --workdir /go/src/github.com/keep-network/keep-core \
      #       go-build-env \
      #       gotestsum --junitfile /mnt/test-results/unit-tests.xml

      # - name: Publish unit test results
      #   uses: EnricoMi/publish-unit-test-result-action@v1.7
      #   if: always() # guarantees that this action always runs, even if earlier steps fail
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     files: ./test-results/unit-tests.xml
      #     check_name: Go Test Results # name under which test results will be presented in GitHub (optional)
      #     comment_on_pr: false # turns off commenting on Pull Requests

  # clean-cache:
  #   if: github.event.pull_request.closed == true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo GITHUB_WORKSPACE:$GITHUB_WORKSPACE
  #         sudo df -h
