name: Solidity

on:
  push:
    branches:
      # TODO: Run only on master after we're fully migrated from Circle CI
      - "rfc-18/**"
      # - master
    paths:
      - "solidity/**"
      - "!solidity/dashboard/**"
      - ".github/workflows/contracts.yml"
  pull_request:
    branches:
      # TODO: Run on all branches or only on master (to be decided)
      # after we're fully migrated from Circle CI
      - "rfc-18/**"
      - master
    paths:
      - "solidity/**"
      - "!solidity/dashboard/**"
      - ".github/workflows/contracts.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        working-directory: ./solidity
        run: npm ci
      - name: Build solidity contracts
        working-directory: ./solidity
        run: npm run compile
      - name: Run tests
        working-directory: ./solidity
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        working-directory: ./solidity
        run: npm ci
      - name: Lint
        working-directory: ./solidity
        run: npm run lint
